driver:
  driver_name: ADAM BIELSKI
  driver_license_number: G0A2025EP2D
  title: Mr.
  gender: his

car_info:
  brand: BYD
  model: VDE U DMI
  vin: LPE1N32H7R1999035
  date_start: 2025.01.08
  date_end: 2025.03.10
  plate_number: W3702P84
